FROM node:24-alpine

RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt

RUN chown -R node:node /opt
USER node

ENV PATH=/opt/node_modules/.bin:$PATH

COPY --chown=node:node package.json package-lock.json ./

# RUN npm config set fetch-retry-maxtimeout 600000 -g &&
ENV NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT=600000
RUN npm ci

WORKDIR /opt/app

COPY --chown=node:node . .

CMD ["npm", "run", "develop"]