FROM node:24-alpine

RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git

ARG PORT
ENV PORT=${PORT}

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN npm i -g npm@latest

WORKDIR /opt/app
COPY . .

RUN chown -R node:node /opt/app
USER node

RUN npm i

EXPOSE ${PORT}

CMD ["npm", "run", "develop"]