services:
  cms:
    container_name: devmat-cms-${BUILD_CONFIG}
    build:
      context: .
      dockerfile: Dockerfile.${BUILD_CONFIG}
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      BUILD_CONFIG: ${BUILD_CONFIG}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
    # command: sleep infinity
    volumes:
      - ./config:/opt/app/config
      - ./database:/opt/app/database
      - ./public:/opt/app/public
      - ./src:/opt/app/src
      - ./types:/opt/app/types
      - ./exports:/opt/app/exports
    #   # expose:
    #   #   - ${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mariadb
    networks:
      common_network:
        ipv4_address: 172.18.0.23

  mariadb:
    container_name: devmat-mariadb
    image: mariadb:12
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PWD}
      - MARIADB_ROOT_HOST=%
      - MARIADB_USER=${DATABASE_USERNAME}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_DATABASE=${DATABASE_NAME}
    # expose:
    #   - 3306
    ports:
      - "3306:3306"
    volumes:
      - ./.db:/var/lib/mysql
    networks:
      common_network:
        ipv4_address: 172.18.0.24

  # phpmyadmin:
  #   container_name: mariadb-ui
  #   image: phpmyadmin:latest
  #   restart: always
  #   env_file: ./.env
  #   environment:
  #     - PMA_HOST=mariadb
  #     - PMA_PORT=3306
  #     - UPLOAD_LIMIT=60M
  #   # expose:
  #   #   - 80
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - "8089:80"

networks:
  common_network:
    external: true
